{% set name = "scikit-hep-testdata" %}
{% set version = "0.5.4" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/scikit-hep/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 50077149aea977bc30e3546b3f7945f39f734db1ad3e3743f05607248bcef982

build:
  number: 0
  noarch: python
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - pyyaml
    - importlib_resources
    - requests

test:
  source_files:
    - tests
  requires:
    - python {{ python_min }}
    - pytest
    - pip
  imports:
    - skhep_testdata
  commands:
    - pip check
    - pytest -vv tests/

about:
  home: https://github.com/scikit-hep/scikit-hep-testdata
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Example HEP files for testing and demonstrating
  doc_url: https://github.com/scikit-hep/scikit-hep-testdata#installing-and-usage
  dev_url: https://github.com/scikit-hep/scikit-hep-testdata/

extra:
  recipe-maintainers:
    - conda-forge/scikit-hep
