{% set name = "scikit-hep-testdata" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/scikit-hep/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 50b7d14d558cd14e8dad4021ae02c3068a29a613be39fbc046fd79c15af56819

build:
  number: 0
  noarch: python
  script: 'SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - setuptools_scm
  run:
    - python >=3.8
    - pyyaml
    - importlib_resources
    - requests

test:
  source_files:
    - tests
  requires:
    - pytest
    - pip
  imports:
    - skhep_testdata
  commands:
    - pip check
    - pytest -vv tests/

about:
  home: https://github.com/scikit-hep/scikit-hep-testdata
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Example HEP files for testing and demonstrating
  doc_url: https://github.com/scikit-hep/scikit-hep-testdata#installing-and-usage
  dev_url: https://github.com/scikit-hep/scikit-hep-testdata/

extra:
  recipe-maintainers:
    - conda-forge/scikit-hep
