{% set name = "scikit-hep-testdata" %}
{% set version = "0.4.44" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/scikit-hep/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 311573ebd5b50f48dd1b8f8eaa420387087483559877604ed27ee2ee76733ea5

build:
  number: 0
  noarch: python
  script: 'SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=2.7
    - pytest-runner
    - setuptools_scm
    - toml  # Workaround for https://github.com/conda-forge/setuptools_scm-feedstock/pull/39
  run:
    - python >=2.7
    - pyyaml
    - importlib_resources
    - requests

test:
  source_files:
    - tests
  requires:
    - pytest
    - pip
  imports:
    - skhep_testdata
  commands:
    - pip check
    - pytest -vv tests/

about:
  home: https://github.com/scikit-hep/scikit-hep-testdata
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Example HEP files for testing and demonstrating
  doc_url: https://github.com/scikit-hep/scikit-hep-testdata#installing-and-usage
  dev_url: https://github.com/scikit-hep/scikit-hep-testdata/

extra:
  recipe-maintainers:
    - conda-forge/scikit-hep
