travis:
  secure:
    BINSTAR_TOKEN: cgBgtybl3zL3bF0ulfiEmLeIdraCB4X3dGPH2wna1ttichWrQCTYH5fTY3eV7xZDUKZroP+mqDf3zVB8axG2bjCu6qdjggfjAf7NNbzJ0MIrKwE4YpwJkGR4AY5dV62SuUDNzt2pitDSFRgTlxaQ84z9STaT5XImm87w3MwDJEfacElol2lq9FZMQb2IW3ydSlhPqAiBzbulTCGqOAKViBK8uHnM3J2XyCCUVnuqKQFOGWR/E2bGUSswc6f8NJ0mMRV5l3Gd4rBsNnclzuncUksLKt15US5MGN8jAiiSdzk3kzQwmkKk+LDv3yFhSPxMsyu/6i17J+Og6dOzXUzZvv6CNRZordIxqd7AVUlaKCQGpoOZBbhTgQ7Ncyo1LYCMz7naSUhavL6XRTWFbBKiQmUa8dv7BKKujwL4q9G2XgZkaJPbyo5MVsAdgYeZ4DQw5fs6bRCiIdi5EzXIxn/Qaq/FVIXVAyQYv+X8/okEMtBTSwfxjRV988da/pkftgxH7IE74TZvMcWQIEsifcFb35Nxa+JLww1FwPbu6h7Eu8oEgnYXFP4+LFdCUcZerrlK7brp1pBdKIJGBcXXXyGyDt/q53FINIxvFJq3Yvo0Tpvu+vXPz5JvZDJwP12OK8IpzXTxMxae2LZIIGSUcsJ0TKKThIdiThCdqkhRJMjH3is=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
